/**
 * Design System - Default Dark Theme
 *
 * Tema oscuro por defecto. Mismo contrato que defaultLight, paleta invertida.
 */

import { palette } from '../tokens/palette';
import {
  baseText,
  baseFonts,
  baseSpace,
  baseRadii,
  baseShadow,
  baseMotion,
  baseIcon,
  baseSizing,
  baseZIndex,
} from './baseTheme';
export const defaultDark = {
  name: 'defaultDark',
  scheme: 'dark',
  color: {
    background: {
      canvas: palette.neutral[950],
      subtle: palette.neutral[900],
      muted: palette.neutral[800],
      inverse: palette.white,
      elevated: palette.darkSurface.elevated,
    },
    surface: {
      base: palette.neutral[900],
      subtle: palette.neutral[800],
      muted: palette.darkSurface.pressed,
      inverse: palette.neutral[100],
      elevated: palette.darkSurface.raised,
      hover: palette.darkSurface.hover,
      pressed: palette.darkSurface.pressed,
      disabled: palette.darkSurface.elevated,
    },
    border: {
      subtle: palette.darkSurface.pressed,
      default: palette.neutral[700],
      strong: palette.neutral[600],
      focus: palette.neutral[100],
      error: palette.red[400],
      success: palette.green[400],
    },
    text: {
      heading: palette.neutral[100],
      body: palette.neutral[100],
      muted: palette.neutral[400],
      subtle: palette.neutral[500],
      disabled: palette.neutral[600],
      placeholder: palette.neutral[600],
      inverse: palette.neutral[900],
      link: palette.blue[400],
      success: palette.green[400],
      warning: palette.amber[400],
      danger: palette.red[400],
      onAction: palette.neutral[900],
    },
    icon: {
      default: palette.neutral[100],
      muted: palette.neutral[400],
      subtle: palette.neutral[500],
      disabled: palette.neutral[600],
      inverse: palette.neutral[900],
      accent: palette.blue[400],
      success: palette.green[400],
      warning: palette.amber[400],
      danger: palette.red[400],
    },
    action: {
      primary: {
        background: palette.gray[100],
        backgroundHover: palette.gray[200],
        backgroundPressed: palette.gray[300],
        backgroundDisabled: palette.darkSurface.pressed,
        text: palette.gray[900],
        textDisabled: palette.neutral[600],
        border: palette.gray[100],
      },
      secondary: {
        background: palette.neutral[800],
        backgroundHover: palette.darkSurface.hover,
        backgroundPressed: palette.darkSurface.pressed,
        backgroundDisabled: palette.darkSurface.elevated,
        text: palette.neutral[100],
        textDisabled: palette.neutral[600],
        border: palette.neutral[700],
      },
      outline: {
        background: 'transparent',
        backgroundHover: palette.darkSurface.hover,
        backgroundPressed: palette.darkSurface.pressed,
        backgroundDisabled: 'transparent',
        text: palette.neutral[100],
        textDisabled: palette.neutral[600],
        border: palette.gray[100],
      },
      ghost: {
        background: 'transparent',
        backgroundHover: palette.darkSurface.hover,
        backgroundPressed: palette.darkSurface.pressed,
        backgroundDisabled: 'transparent',
        text: palette.neutral[100],
        textDisabled: palette.neutral[600],
        border: 'transparent',
      },
      danger: {
        background: palette.red[600],
        backgroundHover: palette.red[700],
        backgroundPressed: palette.red[800],
        backgroundDisabled: palette.darkSurface.pressed,
        text: palette.white,
        textDisabled: palette.neutral[600],
        border: palette.red[600],
      },
      success: {
        background: palette.green[600],
        backgroundHover: palette.green[700],
        backgroundPressed: palette.green[800],
        backgroundDisabled: palette.darkSurface.pressed,
        text: palette.white,
        textDisabled: palette.neutral[600],
        border: palette.green[600],
      },
    },
    state: {
      success: {
        background: palette.green[800],
        text: palette.green[200],
        border: palette.green[500],
      },
      warning: {
        background: palette.amber[800],
        text: palette.amber[200],
        border: palette.amber[500],
      },
      danger: { background: palette.red[800], text: palette.red[200], border: palette.red[500] },
      info: { background: palette.blue[800], text: palette.blue[200], border: palette.blue[500] },
      active: {
        background: palette.green[800],
        text: palette.green[200],
        border: palette.green[500],
      },
      pending: {
        background: palette.amber[800],
        text: palette.amber[200],
        border: palette.amber[500],
      },
      draft: {
        background: palette.darkSurface.pressed,
        text: palette.neutral[400],
        border: palette.neutral[600],
      },
      completed: {
        background: palette.blue[800],
        text: palette.blue[200],
        border: palette.blue[500],
      },
      cancelled: { background: palette.red[800], text: palette.red[200], border: palette.red[500] },
      overdue: { background: palette.red[900], text: palette.red[100], border: palette.red[600] },
      paid: {
        background: palette.emerald[800],
        text: palette.emerald[200],
        border: palette.emerald[500],
      },
      partial: {
        background: palette.amber[900],
        text: palette.amber[100],
        border: palette.amber[600],
      },
    },
    chart: {
      up: palette.green[400],
      down: palette.red[400],
      neutral: palette.neutral[500],
      grid: palette.darkSurface.pressed,
      axis: palette.neutral[400],
      categorical: [
        palette.blue[400],
        palette.green[400],
        palette.amber[400],
        palette.red[400],
        palette.sky[400],
        palette.neutral[400],
        palette.emerald[500],
        palette.blue[300],
      ],
    },
    brand: {
      primary: palette.gray[100],
      primarySoft: palette.neutral[800],
      accent: palette.blue[400],
      accentSoft: palette.blue[800],
      headerFrom: palette.blue[800],
      headerTo: palette.neutral[900],
      onHeader: palette.white,
      onHeaderMuted: palette.alpha.white70,
      headerBorder: palette.alpha.white30,
      headerBadge: palette.alpha.white15,
      avatarFrom: palette.blue[400],
      avatarTo: palette.blue[600],
    },
    overlay: {
      subtle: palette.alpha.black50,
      medium: palette.alpha.black70,
      strong: palette.alpha.black85,
    },
    shadow: palette.black,
  },
  text: baseText,
  fonts: baseFonts,
  space: baseSpace,
  radii: baseRadii,
  shadow: baseShadow,
  motion: baseMotion,
  density: 'comfortable',
  icon: baseIcon,
  sizing: baseSizing,
  zIndex: baseZIndex,
};

export default defaultDark;
