/**
 * Design System - Default Light Theme
 *
 * Tema claro por defecto. Construido sobre la paleta cruda + slots base.
 */

import { palette } from '../tokens/palette';
import {
  baseText,
  baseFonts,
  baseSpace,
  baseRadii,
  baseShadow,
  baseMotion,
  baseIcon,
  baseSizing,
  baseZIndex,
} from './baseTheme';

export const defaultLight = {
  name: 'defaultLight',
  scheme: 'light',
  color: {
    background: {
      canvas: palette.white,
      subtle: palette.neutral[50],
      muted: palette.neutral[100],
      inverse: palette.neutral[900],
      elevated: palette.white,
    },
    surface: {
      base: palette.white,
      subtle: palette.neutral[50],
      muted: palette.neutral[100],
      inverse: palette.neutral[800],
      elevated: palette.white,
      hover: palette.neutral[100],
      pressed: palette.neutral[200],
      disabled: palette.neutral[50],
    },
    border: {
      subtle: palette.neutral[200],
      default: palette.neutral[300],
      strong: palette.neutral[400],
      focus: palette.gray[900],
      error: palette.red[500],
      success: palette.green[500],
    },
    text: {
      heading: palette.neutral[900],
      body: palette.neutral[900],
      muted: palette.neutral[600],
      subtle: palette.neutral[500],
      disabled: palette.neutral[400],
      placeholder: palette.neutral[400],
      inverse: palette.white,
      link: palette.blue[500],
      success: palette.green[600],
      warning: palette.amber[600],
      danger: palette.red[600],
      onAction: palette.white,
    },
    icon: {
      default: palette.neutral[900],
      muted: palette.neutral[600],
      subtle: palette.neutral[500],
      disabled: palette.neutral[400],
      inverse: palette.white,
      accent: palette.blue[500],
      success: palette.green[500],
      warning: palette.amber[500],
      danger: palette.red[500],
    },
    action: {
      primary: {
        background: palette.gray[900],
        backgroundHover: palette.gray[800],
        backgroundPressed: palette.gray[700],
        backgroundDisabled: palette.neutral[200],
        text: palette.white,
        textDisabled: palette.neutral[400],
        border: palette.gray[900],
      },
      secondary: {
        background: palette.neutral[100],
        backgroundHover: palette.neutral[200],
        backgroundPressed: palette.neutral[300],
        backgroundDisabled: palette.neutral[50],
        text: palette.neutral[900],
        textDisabled: palette.neutral[400],
        border: palette.neutral[200],
      },
      outline: {
        background: 'transparent',
        backgroundHover: palette.neutral[100],
        backgroundPressed: palette.neutral[200],
        backgroundDisabled: 'transparent',
        text: palette.neutral[900],
        textDisabled: palette.neutral[400],
        border: palette.gray[900],
      },
      ghost: {
        background: 'transparent',
        backgroundHover: palette.neutral[100],
        backgroundPressed: palette.neutral[200],
        backgroundDisabled: 'transparent',
        text: palette.neutral[900],
        textDisabled: palette.neutral[400],
        border: 'transparent',
      },
      danger: {
        background: palette.red[600],
        backgroundHover: palette.red[700],
        backgroundPressed: palette.red[800],
        backgroundDisabled: palette.neutral[200],
        text: palette.white,
        textDisabled: palette.neutral[400],
        border: palette.red[600],
      },
      success: {
        background: palette.green[600],
        backgroundHover: palette.green[700],
        backgroundPressed: palette.green[800],
        backgroundDisabled: palette.neutral[200],
        text: palette.white,
        textDisabled: palette.neutral[400],
        border: palette.green[600],
      },
    },
    state: {
      success: {
        background: palette.green[100],
        text: palette.green[800],
        border: palette.green[500],
      },
      warning: {
        background: palette.amber[100],
        text: palette.amber[800],
        border: palette.amber[500],
      },
      danger: { background: palette.red[100], text: palette.red[800], border: palette.red[500] },
      info: { background: palette.blue[100], text: palette.blue[800], border: palette.blue[500] },
      active: {
        background: palette.green[100],
        text: palette.green[800],
        border: palette.green[500],
      },
      pending: {
        background: palette.amber[100],
        text: palette.amber[800],
        border: palette.amber[500],
      },
      draft: {
        background: palette.neutral[100],
        text: palette.neutral[600],
        border: palette.neutral[300],
      },
      completed: {
        background: palette.blue[100],
        text: palette.blue[800],
        border: palette.blue[500],
      },
      cancelled: { background: palette.red[100], text: palette.red[800], border: palette.red[500] },
      overdue: { background: palette.red[100], text: palette.red[900], border: palette.red[600] },
      paid: {
        background: palette.emerald[100],
        text: palette.emerald[800],
        border: palette.emerald[500],
      },
      partial: {
        background: palette.amber[100],
        text: palette.amber[900],
        border: palette.amber[600],
      },
    },
    chart: {
      up: palette.green[600],
      down: palette.red[600],
      neutral: palette.neutral[400],
      grid: palette.neutral[200],
      axis: palette.neutral[500],
      categorical: [
        palette.blue[500],
        palette.green[500],
        palette.amber[500],
        palette.red[500],
        palette.sky[500],
        palette.neutral[500],
        palette.emerald[500],
        palette.blue[700],
      ],
    },
    brand: {
      primary: palette.gray[900],
      primarySoft: palette.neutral[100],
      accent: palette.blue[500],
      accentSoft: palette.blue[100],
      headerFrom: palette.blue[100],
      headerTo: palette.white,
      onHeader: palette.neutral[900],
      onHeaderMuted: palette.alpha.black70,
      headerBorder: palette.alpha.black15,
      headerBadge: palette.alpha.black10,
      avatarFrom: palette.blue[400],
      avatarTo: palette.blue[600],
    },
    overlay: {
      subtle: palette.alpha.black30,
      medium: palette.alpha.black50,
      strong: palette.alpha.black70,
    },
    shadow: palette.black,
  },
  text: baseText,
  fonts: baseFonts,
  space: baseSpace,
  radii: baseRadii,
  shadow: baseShadow,
  motion: baseMotion,
  density: 'comfortable' as const,
  icon: baseIcon,
  sizing: baseSizing,
  zIndex: baseZIndex,
};

export type Theme = typeof defaultLight & { scheme: 'light' | 'dark'; name: string };
export default defaultLight;
