"use strict";
/**
 * Design System - Default Light Theme
 *
 * Tema claro por defecto. Construido sobre la paleta cruda + slots base.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.defaultLight = void 0;
const palette_1 = require("../tokens/palette");
const baseTheme_1 = require("./baseTheme");
exports.defaultLight = {
    name: 'defaultLight',
    scheme: 'light',
    color: {
        background: {
            canvas: palette_1.palette.white,
            subtle: palette_1.palette.neutral[50],
            muted: palette_1.palette.neutral[100],
            inverse: palette_1.palette.neutral[900],
            elevated: palette_1.palette.white,
        },
        surface: {
            base: palette_1.palette.white,
            subtle: palette_1.palette.neutral[50],
            muted: palette_1.palette.neutral[100],
            inverse: palette_1.palette.neutral[800],
            elevated: palette_1.palette.white,
            hover: palette_1.palette.neutral[100],
            pressed: palette_1.palette.neutral[200],
            disabled: palette_1.palette.neutral[50],
        },
        border: {
            subtle: palette_1.palette.neutral[200],
            default: palette_1.palette.neutral[300],
            strong: palette_1.palette.neutral[400],
            focus: palette_1.palette.gray[900],
            error: palette_1.palette.red[500],
            success: palette_1.palette.green[500],
        },
        text: {
            heading: palette_1.palette.neutral[900],
            body: palette_1.palette.neutral[900],
            muted: palette_1.palette.neutral[600],
            subtle: palette_1.palette.neutral[500],
            disabled: palette_1.palette.neutral[400],
            placeholder: palette_1.palette.neutral[400],
            inverse: palette_1.palette.white,
            link: palette_1.palette.blue[500],
            success: palette_1.palette.green[600],
            warning: palette_1.palette.amber[600],
            danger: palette_1.palette.red[600],
            onAction: palette_1.palette.white,
        },
        icon: {
            default: palette_1.palette.neutral[900],
            muted: palette_1.palette.neutral[600],
            subtle: palette_1.palette.neutral[500],
            disabled: palette_1.palette.neutral[400],
            inverse: palette_1.palette.white,
            accent: palette_1.palette.blue[500],
            success: palette_1.palette.green[500],
            warning: palette_1.palette.amber[500],
            danger: palette_1.palette.red[500],
        },
        action: {
            primary: {
                background: palette_1.palette.gray[900],
                backgroundHover: palette_1.palette.gray[800],
                backgroundPressed: palette_1.palette.gray[700],
                backgroundDisabled: palette_1.palette.neutral[200],
                text: palette_1.palette.white,
                textDisabled: palette_1.palette.neutral[400],
                border: palette_1.palette.gray[900],
            },
            secondary: {
                background: palette_1.palette.neutral[100],
                backgroundHover: palette_1.palette.neutral[200],
                backgroundPressed: palette_1.palette.neutral[300],
                backgroundDisabled: palette_1.palette.neutral[50],
                text: palette_1.palette.neutral[900],
                textDisabled: palette_1.palette.neutral[400],
                border: palette_1.palette.neutral[200],
            },
            outline: {
                background: 'transparent',
                backgroundHover: palette_1.palette.neutral[100],
                backgroundPressed: palette_1.palette.neutral[200],
                backgroundDisabled: 'transparent',
                text: palette_1.palette.neutral[900],
                textDisabled: palette_1.palette.neutral[400],
                border: palette_1.palette.gray[900],
            },
            ghost: {
                background: 'transparent',
                backgroundHover: palette_1.palette.neutral[100],
                backgroundPressed: palette_1.palette.neutral[200],
                backgroundDisabled: 'transparent',
                text: palette_1.palette.neutral[900],
                textDisabled: palette_1.palette.neutral[400],
                border: 'transparent',
            },
            danger: {
                background: palette_1.palette.red[600],
                backgroundHover: palette_1.palette.red[700],
                backgroundPressed: palette_1.palette.red[800],
                backgroundDisabled: palette_1.palette.neutral[200],
                text: palette_1.palette.white,
                textDisabled: palette_1.palette.neutral[400],
                border: palette_1.palette.red[600],
            },
            success: {
                background: palette_1.palette.green[600],
                backgroundHover: palette_1.palette.green[700],
                backgroundPressed: palette_1.palette.green[800],
                backgroundDisabled: palette_1.palette.neutral[200],
                text: palette_1.palette.white,
                textDisabled: palette_1.palette.neutral[400],
                border: palette_1.palette.green[600],
            },
        },
        state: {
            success: {
                background: palette_1.palette.green[100],
                text: palette_1.palette.green[800],
                border: palette_1.palette.green[500],
            },
            warning: {
                background: palette_1.palette.amber[100],
                text: palette_1.palette.amber[800],
                border: palette_1.palette.amber[500],
            },
            danger: { background: palette_1.palette.red[100], text: palette_1.palette.red[800], border: palette_1.palette.red[500] },
            info: { background: palette_1.palette.blue[100], text: palette_1.palette.blue[800], border: palette_1.palette.blue[500] },
            active: {
                background: palette_1.palette.green[100],
                text: palette_1.palette.green[800],
                border: palette_1.palette.green[500],
            },
            pending: {
                background: palette_1.palette.amber[100],
                text: palette_1.palette.amber[800],
                border: palette_1.palette.amber[500],
            },
            draft: {
                background: palette_1.palette.neutral[100],
                text: palette_1.palette.neutral[600],
                border: palette_1.palette.neutral[300],
            },
            completed: {
                background: palette_1.palette.blue[100],
                text: palette_1.palette.blue[800],
                border: palette_1.palette.blue[500],
            },
            cancelled: { background: palette_1.palette.red[100], text: palette_1.palette.red[800], border: palette_1.palette.red[500] },
            overdue: { background: palette_1.palette.red[100], text: palette_1.palette.red[900], border: palette_1.palette.red[600] },
            paid: {
                background: palette_1.palette.emerald[100],
                text: palette_1.palette.emerald[800],
                border: palette_1.palette.emerald[500],
            },
            partial: {
                background: palette_1.palette.amber[100],
                text: palette_1.palette.amber[900],
                border: palette_1.palette.amber[600],
            },
        },
        chart: {
            up: palette_1.palette.green[600],
            down: palette_1.palette.red[600],
            neutral: palette_1.palette.neutral[400],
            grid: palette_1.palette.neutral[200],
            axis: palette_1.palette.neutral[500],
            categorical: [
                palette_1.palette.blue[500],
                palette_1.palette.green[500],
                palette_1.palette.amber[500],
                palette_1.palette.red[500],
                palette_1.palette.sky[500],
                palette_1.palette.neutral[500],
                palette_1.palette.emerald[500],
                palette_1.palette.blue[700],
            ],
        },
        brand: {
            primary: palette_1.palette.gray[900],
            primarySoft: palette_1.palette.neutral[100],
            accent: palette_1.palette.blue[500],
            accentSoft: palette_1.palette.blue[100],
            headerFrom: palette_1.palette.blue[100],
            headerTo: palette_1.palette.white,
            onHeader: palette_1.palette.neutral[900],
            onHeaderMuted: palette_1.palette.alpha.black70,
            headerBorder: palette_1.palette.alpha.black15,
            headerBadge: palette_1.palette.alpha.black10,
            avatarFrom: palette_1.palette.blue[400],
            avatarTo: palette_1.palette.blue[600],
        },
        overlay: {
            subtle: palette_1.palette.alpha.black30,
            medium: palette_1.palette.alpha.black50,
            strong: palette_1.palette.alpha.black70,
        },
        shadow: palette_1.palette.black,
    },
    text: baseTheme_1.baseText,
    fonts: baseTheme_1.baseFonts,
    space: baseTheme_1.baseSpace,
    radii: baseTheme_1.baseRadii,
    shadow: baseTheme_1.baseShadow,
    motion: baseTheme_1.baseMotion,
    density: 'comfortable',
    icon: baseTheme_1.baseIcon,
    sizing: baseTheme_1.baseSizing,
    zIndex: baseTheme_1.baseZIndex,
};
exports.default = exports.defaultLight;
