"use strict";
/**
 * Design System - Default Dark Theme
 *
 * Tema oscuro por defecto. Mismo contrato que defaultLight, paleta invertida.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.defaultDark = void 0;
const palette_1 = require("../tokens/palette");
const baseTheme_1 = require("./baseTheme");
exports.defaultDark = {
    name: 'defaultDark',
    scheme: 'dark',
    color: {
        background: {
            canvas: palette_1.palette.neutral[950],
            subtle: palette_1.palette.neutral[900],
            muted: palette_1.palette.neutral[800],
            inverse: palette_1.palette.white,
            elevated: palette_1.palette.darkSurface.elevated,
        },
        surface: {
            base: palette_1.palette.neutral[900],
            subtle: palette_1.palette.neutral[800],
            muted: palette_1.palette.darkSurface.pressed,
            inverse: palette_1.palette.neutral[100],
            elevated: palette_1.palette.darkSurface.raised,
            hover: palette_1.palette.darkSurface.hover,
            pressed: palette_1.palette.darkSurface.pressed,
            disabled: palette_1.palette.darkSurface.elevated,
        },
        border: {
            subtle: palette_1.palette.darkSurface.pressed,
            default: palette_1.palette.neutral[700],
            strong: palette_1.palette.neutral[600],
            focus: palette_1.palette.neutral[100],
            error: palette_1.palette.red[400],
            success: palette_1.palette.green[400],
        },
        text: {
            heading: palette_1.palette.neutral[100],
            body: palette_1.palette.neutral[100],
            muted: palette_1.palette.neutral[400],
            subtle: palette_1.palette.neutral[500],
            disabled: palette_1.palette.neutral[600],
            placeholder: palette_1.palette.neutral[600],
            inverse: palette_1.palette.neutral[900],
            link: palette_1.palette.blue[400],
            success: palette_1.palette.green[400],
            warning: palette_1.palette.amber[400],
            danger: palette_1.palette.red[400],
            onAction: palette_1.palette.neutral[900],
        },
        icon: {
            default: palette_1.palette.neutral[100],
            muted: palette_1.palette.neutral[400],
            subtle: palette_1.palette.neutral[500],
            disabled: palette_1.palette.neutral[600],
            inverse: palette_1.palette.neutral[900],
            accent: palette_1.palette.blue[400],
            success: palette_1.palette.green[400],
            warning: palette_1.palette.amber[400],
            danger: palette_1.palette.red[400],
        },
        action: {
            primary: {
                background: palette_1.palette.gray[100],
                backgroundHover: palette_1.palette.gray[200],
                backgroundPressed: palette_1.palette.gray[300],
                backgroundDisabled: palette_1.palette.darkSurface.pressed,
                text: palette_1.palette.gray[900],
                textDisabled: palette_1.palette.neutral[600],
                border: palette_1.palette.gray[100],
            },
            secondary: {
                background: palette_1.palette.neutral[800],
                backgroundHover: palette_1.palette.darkSurface.hover,
                backgroundPressed: palette_1.palette.darkSurface.pressed,
                backgroundDisabled: palette_1.palette.darkSurface.elevated,
                text: palette_1.palette.neutral[100],
                textDisabled: palette_1.palette.neutral[600],
                border: palette_1.palette.neutral[700],
            },
            outline: {
                background: 'transparent',
                backgroundHover: palette_1.palette.darkSurface.hover,
                backgroundPressed: palette_1.palette.darkSurface.pressed,
                backgroundDisabled: 'transparent',
                text: palette_1.palette.neutral[100],
                textDisabled: palette_1.palette.neutral[600],
                border: palette_1.palette.gray[100],
            },
            ghost: {
                background: 'transparent',
                backgroundHover: palette_1.palette.darkSurface.hover,
                backgroundPressed: palette_1.palette.darkSurface.pressed,
                backgroundDisabled: 'transparent',
                text: palette_1.palette.neutral[100],
                textDisabled: palette_1.palette.neutral[600],
                border: 'transparent',
            },
            danger: {
                background: palette_1.palette.red[600],
                backgroundHover: palette_1.palette.red[700],
                backgroundPressed: palette_1.palette.red[800],
                backgroundDisabled: palette_1.palette.darkSurface.pressed,
                text: palette_1.palette.white,
                textDisabled: palette_1.palette.neutral[600],
                border: palette_1.palette.red[600],
            },
            success: {
                background: palette_1.palette.green[600],
                backgroundHover: palette_1.palette.green[700],
                backgroundPressed: palette_1.palette.green[800],
                backgroundDisabled: palette_1.palette.darkSurface.pressed,
                text: palette_1.palette.white,
                textDisabled: palette_1.palette.neutral[600],
                border: palette_1.palette.green[600],
            },
        },
        state: {
            success: {
                background: palette_1.palette.green[800],
                text: palette_1.palette.green[200],
                border: palette_1.palette.green[500],
            },
            warning: {
                background: palette_1.palette.amber[800],
                text: palette_1.palette.amber[200],
                border: palette_1.palette.amber[500],
            },
            danger: { background: palette_1.palette.red[800], text: palette_1.palette.red[200], border: palette_1.palette.red[500] },
            info: { background: palette_1.palette.blue[800], text: palette_1.palette.blue[200], border: palette_1.palette.blue[500] },
            active: {
                background: palette_1.palette.green[800],
                text: palette_1.palette.green[200],
                border: palette_1.palette.green[500],
            },
            pending: {
                background: palette_1.palette.amber[800],
                text: palette_1.palette.amber[200],
                border: palette_1.palette.amber[500],
            },
            draft: {
                background: palette_1.palette.darkSurface.pressed,
                text: palette_1.palette.neutral[400],
                border: palette_1.palette.neutral[600],
            },
            completed: {
                background: palette_1.palette.blue[800],
                text: palette_1.palette.blue[200],
                border: palette_1.palette.blue[500],
            },
            cancelled: { background: palette_1.palette.red[800], text: palette_1.palette.red[200], border: palette_1.palette.red[500] },
            overdue: { background: palette_1.palette.red[900], text: palette_1.palette.red[100], border: palette_1.palette.red[600] },
            paid: {
                background: palette_1.palette.emerald[800],
                text: palette_1.palette.emerald[200],
                border: palette_1.palette.emerald[500],
            },
            partial: {
                background: palette_1.palette.amber[900],
                text: palette_1.palette.amber[100],
                border: palette_1.palette.amber[600],
            },
        },
        chart: {
            up: palette_1.palette.green[400],
            down: palette_1.palette.red[400],
            neutral: palette_1.palette.neutral[500],
            grid: palette_1.palette.darkSurface.pressed,
            axis: palette_1.palette.neutral[400],
            categorical: [
                palette_1.palette.blue[400],
                palette_1.palette.green[400],
                palette_1.palette.amber[400],
                palette_1.palette.red[400],
                palette_1.palette.sky[400],
                palette_1.palette.neutral[400],
                palette_1.palette.emerald[500],
                palette_1.palette.blue[300],
            ],
        },
        brand: {
            primary: palette_1.palette.gray[100],
            primarySoft: palette_1.palette.neutral[800],
            accent: palette_1.palette.blue[400],
            accentSoft: palette_1.palette.blue[800],
            headerFrom: palette_1.palette.blue[800],
            headerTo: palette_1.palette.neutral[900],
            onHeader: palette_1.palette.white,
            onHeaderMuted: palette_1.palette.alpha.white70,
            headerBorder: palette_1.palette.alpha.white30,
            headerBadge: palette_1.palette.alpha.white15,
            avatarFrom: palette_1.palette.blue[400],
            avatarTo: palette_1.palette.blue[600],
        },
        overlay: {
            subtle: palette_1.palette.alpha.black50,
            medium: palette_1.palette.alpha.black70,
            strong: palette_1.palette.alpha.black85,
        },
        shadow: palette_1.palette.black,
    },
    text: baseTheme_1.baseText,
    fonts: baseTheme_1.baseFonts,
    space: baseTheme_1.baseSpace,
    radii: baseTheme_1.baseRadii,
    shadow: baseTheme_1.baseShadow,
    motion: baseTheme_1.baseMotion,
    density: 'comfortable',
    icon: baseTheme_1.baseIcon,
    sizing: baseTheme_1.baseSizing,
    zIndex: baseTheme_1.baseZIndex,
};
exports.default = exports.defaultDark;
